### ISSUE TITLE
Implementations in other languages

### ISSUE THREAD

**Issue by errhammr** [preshing/RandomSequence#2]
I've reimplemented this project in [python3](https://codeberg.org/errhammr/py3-random-sequence-of-unique) and [rust](https://codeberg.org/errhammr/rust-random-sequence) just for fun.
Those implementations should produce the same sequence of numbers as this C++ version, assuming that an `unsigned int` is 32 bits in length. (When initialized with `RandomSequenceOfUnique rsu(0, 1);`, the first 20 integers are the same, which is good enough of a test for my spare time projects)

I'm not requesting that you link my repos in the readme if you don't want to. I just want to leave a note here so that other people might find them if they are determined enough to look for them.

**Comment by preshing** [comment]
Cool, thanks for the note.

**Comment by NickStrupat** [comment]
I also implemented this in C#, both the 32-bit one and a 64-bit port.

https://gist.github.com/NickStrupat/464b3f63bfad7d780fada2974ae62a8f
